name: Latest blog posts

on:
  schedule:
    # Runs at 6am UTC every Monday
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://thomasthornton.cloud/feed/"
          max_post_count: 5
          readme_path: README.md
          comment_tag_name: BLOG-POST-LIST
          gh_token: ${{ secrets.GITHUB_TOKEN }}
